version: 1.2
workflows:
  - name: mango_trio
    subclass: WDL
    primaryDescriptorPath: /wdl/mango_trio.wdl
    testParameterFiles:
      - /wdl/inputs.template.json
    readMePath: /wdl/README.md
    authors:
      - name: MANGO
